### PR TITLE
Revive SectionSample

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Properly removing the major so that downstream can test

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I yanked the latest release because it was broken. Somehow there was a hidden major version bump (https://github.com/SciML/QuasiMonteCarlo.jl/commit/eb79d905e509d2ec357c21acfa901c8e15bb2d91) that blocked all downstream testing. @ParadaCarleton how did that happen, I didn't see it in the PR? Because of that, it ignored downstream testing and what looked like all passing was all failure.

This is highlighting the current issue:

https://github.com/SciML/QuasiMonteCarlo.jl/actions/runs/3711087884/jobs/6291172128

We should not do any more substantive changes until downstream was fixed. I was under the impression that was what https://github.com/SciML/QuasiMonteCarlo.jl/pull/65 was for, but all it did was set a major bump too early in order to turn off downstream tests.

**Comment by ParadaCarleton** [comment]
#65 included a fix to `KroneckerSample` that should correct that particular issue with Surrogates.jl, alongside a lot of other bug fixes and cleanup, including removal of functions that were broken (most of which silently produce incorrect results). I can make a PR that applies only the changes for just the one fix, but it should be noted such a release would include a lot of incorrect code--the PR I made was a complete overhaul aimed at making the codebase manageable and stripping out everything broken (in places where it couldn't be corrected without making anything break).

I can reimplement the specific fix (which just starts `KroneckerSample` at a different point) as a separate patch on the earlier version, but to be clear, this would involve leaving a lot of incorrect code untouched.

**Comment by ChrisRackauckas** [comment]
So what would be your suggestion for how to get the Surrogates.jl tests passing without simply removing Surrogates.jl tests and functionality? That should be the main goal right now: tests should always be passing. As of right now, we cannot do any releases of QuasiMonteCarlo.jl as its master is "broken" in the sense of downstream.

**Comment by ChrisRackauckas** [comment]
Maybe the right thing to do then would be to change downstream libraries to avoid these samplers in their tests? I think SurrogatesAbstractGP is doing something special with SectionSampler though. Pinging @vikram-s-narayan

**Comment by ParadaCarleton** [comment]
> Maybe the right thing to do then would be to change downstream libraries to avoid these samplers in their tests? I think SurrogatesAbstractGP is doing something special with SectionSampler though. Pinging @vikram-s-narayan

I think that makes sense. Maybe we could set up a call about making sure Surrogates.jl works well together with QMC.jl?

**Comment by vikram-s-narayan** [comment]
> Maybe the right thing to do then would be to change downstream libraries to avoid these samplers in their tests? I think SurrogatesAbstractGP is doing something special with SectionSampler though. Pinging @vikram-s-narayan

[SurrogatesAbstractGPs](https://github.com/SciML/Surrogates.jl/tree/master/lib/SurrogatesAbstractGPs) _does not_ use SectionSampler in either the [source files](https://github.com/SciML/Surrogates.jl/blob/master/lib/SurrogatesAbstractGPs/src/SurrogatesAbstractGPs.jl), the [test files](https://github.com/SciML/Surrogates.jl/blob/master/lib/SurrogatesAbstractGPs/test/runtests.jl) or the [documentation](https://docs.sciml.ai/Surrogates/stable/abstractgps/).

However, SurrogatesAbstractGPs does use  UniformSample in two of the tests (Optimization tests for [1D](https://github.com/SciML/Surrogates.jl/blob/ac4ab31b26c905ad961f7f9d09f5b22cd0fe1e1d/lib/SurrogatesAbstractGPs/test/runtests.jl#L90) and [ND](https://github.com/SciML/Surrogates.jl/blob/ac4ab31b26c905ad961f7f9d09f5b22cd0fe1e1d/lib/SurrogatesAbstractGPs/test/runtests.jl#L102))

**Comment by vikram-s-narayan** [comment]
> I think that makes sense. Maybe we could set up a call about making sure Surrogates.jl works well together with QMC.jl?

@ParadaCarleton - happy to jump on to a call. However, because of the time zone differences (I'm based in India), scheduling may be trickier. Alternatively, we can work via GitHub issues and PR's itself. As I understand it, what we need to do now is: 

1. Remove all references to SectionSampler and try to replace with an alternative sampler or remove those test cases that use SectionSampler. In case, there is a major breaker (example a Surrogate not working because of its dependence on SectionSampler), I will flag it to get your input on it.
2. Change instances where UniformSample is used and replace with RandomSample. 

Is my understanding correct?

**Comment by ParadaCarleton** [comment]
> @ChrisRackauckas, as I understand it, what we need to do now is:
> 
> 1. Remove all references to SectionSampler and try to replace with an alternative sampler or remove those test cases that use SectionSampler. In case, there is a major breaker (example a Surrogate not working because of its dependence on SectionSampler), I will flag it to get your input on it. Also, we need to double check if anything will break without SectionSampler (ex: [Surrogate optimization](https://github.com/SciML/Surrogates.jl/blob/master/src/Optimization.jl#L1776)).
> 2. Change instances where UniformSample is used and replace with RandomSample.
> 
> Is my understanding correct?

I think that's correct.

If `SectionSampler` is not actually being used in Surrogates, the only thing that should cause a problem would be using `UniformSample` instead of `RandomSample`. If there's something else broken, let me know, because that and `SectionSample` are the only things that should no longer be compatible with the new version--I'll put out a bug fix for those.

**Comment by vikram-s-narayan** [comment]
> If `SectionSampler` is not actually being used in Surrogates, the only thing that should cause a problem would be using `UniformSample` instead of `RandomSample`. If there's something else broken, let me know, because that and `SectionSample` are the only things that should no longer be compatible with the new version--I'll put out a bug fix for those.

SectionSampler is a necessary part of surrogate optimization because some values are held constant in a particular dimension while exploring other points in that region ([view example](https://github.com/SciML/Surrogates.jl/blob/ac4ab31b26c905ad961f7f9d09f5b22cd0fe1e1d/test/optimization.jl#L191)). Hence, it needs to be retained.

**Comment by ChrisRackauckas** [comment]
> If SectionSampler is not actually being used in Surrogates

It is being used in Surrogates directly, I think it's the only one.

But as @vikram-s-narayan said, it's a very specific purpose of only integrating subsets. Maybe that means it should be a tool that is internal to Surrogates, not even documented, since it seems like it's something that's supposed to be internal to the Surrogate optimization's process? Otherwise it would need to be documented here as some separate special method for sampling within a subset of space?

**Comment by ParadaCarleton** [comment]
> > If SectionSampler is not actually being used in Surrogates
> 
> It is being used in Surrogates directly, I think it's the only one.
> 
> But as @vikram-s-narayan said, it's a very specific purpose of only integrating subsets. Maybe that means it should be a tool that is internal to Surrogates, not even documented, since it seems like it's something that's supposed to be internal to the Surrogate optimization's process? Otherwise it would need to be documented here as some separate special method for sampling within a subset of space?

I think so--if Surrogates.jl happens to need a set of QMC points for a function holding some dimensions constant, they can generate those points pretty easily without having to append another sampler to QMC.jl. The only thing you need to do is generate a `d - fixed_dims`-dimensional RQMC sequence; with #57 this should be easy. (But without randomization, the points will be very low-quality, because many of them will overlap with previous points.) 

My suggestion for a temporary fix is to use Latin Hypercube samples (which are already fully randomized, and have a "do no harm" property that guarantees the performance is never worse than Monte Carlo); later, when we have randomization, we can change the code to use the same sampler for the subsequences.

**Comment by ChrisRackauckas** [comment]
Let's go with the Latin Hypercube approach.

**Comment by ParadaCarleton** [comment]
> Let's go with the Latin Hypercube approach.

Got it, I think that makes sense. So, I can add back `SectionSample`, but as mentioned before, I think this is a Surrogates.jl-specific functionality that's not really related to Quasi Monte Carlo points.

@vikram-s-narayan can I ask, what is Surrogates.jl using `SectionSample` for? Is it trying to identify the most important dimensions to refine the surrogate along? i.e. is it identifying which dimensions need to be sampled most densely, or have the greatest amount of variation?

**Comment by ParadaCarleton** [comment]
The reason I ask is because if you're trying to avoid any assumptions about which dimensions are the most important, the only appropriate nets are the Faure sequence and the Latin Hypercube Samples, which stratify along all dimensions equally. Sobol points basically assume you've already ordered all dimensions from most to least important, and exploring the highest dimensions is unnecessary. e.g. the dimensions might be the principal components. Sobol points go all-in on stratifying the first few dimensions, at the cost of appallingly bad distributions for the highest dimensions. Here's the 38th and 39th dimensions:
image

In general, for the `d`th dimension of a Sobol sample to be well-stratified, you need more than `O(2^d)` points. That's fine if the last few dimensions have close to 0 variation, but poses a big problem if they're also important.

**Comment by vikram-s-narayan** [comment]
@ParadaCarleton - Below are the responses to your questions. 

1. What is Surrogates.jl using SectionSample for?
SectionSample is being used in a type of [optimization function](https://github.com/SciML/Surrogates.jl/blob/ac4ab31b26c905ad961f7f9d09f5b22cd0fe1e1d/src/Optimization.jl#L1776)  


2. Is it trying to identify the most important dimensions to refine the surrogate along? i.e. is it identifying which dimensions need to be sampled most densely, or have the greatest amount of variation?
No. It's being used to generate sample points while holding a particular dimension constant.

**Comment by ParadaCarleton** [comment]
Got it. In that case, LHS is the best approach for a temporary fix. But as mentioned, I don't think `SectionSampler` belongs here, since it seems to be unrelated to QMC. It looks like what you're doing is just partial application, which shouldn't require a new sampler to do.

**Comment by ParadaCarleton** [comment]
@vikram-s-narayan Got it. In that case, LHS is the best approach for a temporary fix. But as mentioned, I don't think `SectionSampler` belongs here, since it seems to be unrelated to QMC. It looks like what you're doing is just partial application, which shouldn't require a new sampler to do.

**Comment by vikram-s-narayan** [comment]
> @vikram-s-narayan Got it. In that case, LHS is the best approach for a temporary fix. But as mentioned, I don't think `SectionSampler` belongs here, since it seems to be unrelated to QMC. It looks like what you're doing is just partial application, which shouldn't require a new sampler.

SectionSampler was indeed a part of Surrogates before it was [moved](https://github.com/SciML/Surrogates.jl/commit/5914e30cf6ef9661cee8a54377014f3b6ecd698c) here. @archermarx, if you have a moment, could you please share why we moved SectionSampler to QuasiMonteCarlo ([related commits here](https://github.com/SciML/QuasiMonteCarlo.jl/commit/75d316b69d86ccaa484555ca8425ba0f3ef70970))?

**Comment by ParadaCarleton** [comment]
> > @vikram-s-narayan Got it. In that case, LHS is the best approach for a temporary fix. But as mentioned, I don't think `SectionSampler` belongs here, since it seems to be unrelated to QMC. It looks like what you're doing is just partial application, which shouldn't require a new sampler.
> 
> SectionSampler was indeed a part of Surrogates before it was [moved](https://github.com/SciML/Surrogates.jl/commit/5914e30cf6ef9661cee8a54377014f3b6ecd698c) to QMC. @archermarx, if you have a moment, could you please share why we moved SectionSampler to QuasiMonteCarlo ([related commits here](https://github.com/SciML/QuasiMonteCarlo.jl/commit/75d316b69d86ccaa484555ca8425ba0f3ef70970))?

Moving SectionSampler back to Surrogates is one possibility, but even that doesn't seem to be necessary. A much simpler approach is just to:
1. Use partial application--define a new function `f_partial = y -> f(fixed_dim_value, y)`, then
2. Request a new sequence from QMC.jl and use that, i.e. iterate through `sample(n, length(free_dims), LatinHypercubeSample())`.

**Comment by ChrisRackauckas** [comment]
> SectionSampler was indeed a part of Surrogates before it was [moved](https://github.com/SciML/Surrogates.jl/commit/5914e30cf6ef9661cee8a54377014f3b6ecd698c) to QMC. @archermarx, if you have a moment, could you please share why we moved SectionSampler to QuasiMonteCarlo ([related commits here](https://github.com/SciML/QuasiMonteCarlo.jl/commit/75d316b69d86ccaa484555ca8425ba0f3ef70970))?

Everything sampling related was moved from Surrogates.jl to its own package because the samplers are a much broader idea than surrogates. There's no reason to require bringing in every RBF etc. if you just want an interface to LatinHypercube, Sobol, etc. the big impetus for getting this done was NeuralPDE.jl and GlobalSensitivity.jl, but of course there's many other applications, like writing numerical integration schemes, where these tools are necessary. So, it was split off to its own package to be lean for downstream.

Now the issue here is that @ParadaCarleton and others are now improving the samplers for the general applications, but it seems Surrogates.jl had this SectionSampler as a hack to subset the sampling. And it doesn't seem like it was quite right either 😅, in the sense that (if I'm following @ParadaCarleton correctly, I don't know the proof of this) its method was not giving a low discrepancy sequence with the right properties to either converge or converge at the accelerated rate. Because of this, it was removed from this package. 

Now the right thing for Surrogates.jl to do is to do this correctly, as otherwise there's no convergence guarantee on the surrogate itself. Not all low discrepency sequences can be restarted in a subset and have the right property, so that makes it difficult to support generally. But as @ParadaCarleton states, LatinHypercube can just subsample in a square and effectively converge correctly. Thus the right thing to do might be to only support that in Surrogates.jl right now by, in the methods that require it, throw an error if a sampler other than LatinHypercube is used, and change the tests to use LatinHypercube. Then in the surrogate optimization schemes, do this subsetting by simply doing new `sample` calls on subsets of the domain.

I think I got this all?

**Comment by ParadaCarleton** [comment]
> I think I got this all?

Basically, except I'd note it's not so much a problem with points other than LHS as it is a problem with our current lack of randomization. Randomizing LHS happens to be trivial, so it's already been done, but other point sets are harder. Once RQMC works, we can use any QMC point set we'd like, as long as we're looking up independent randomizations.

**Comment by ParadaCarleton** [comment]
@vikram-s-narayan RQMC has been added, it should be possible to fix this now. I think `generate_design_matrices` should do what you want.

**Comment by ParadaCarleton** [comment]
What happened with this PR--is it still needed?

**Comment by ChrisRackauckas** [comment]
@sharanry related.

**Pull request closed without merging**
