### PR TITLE
Move Kronecker, SectionSample, and GoldenSample from Surrogates.jl

### PR DESCRIPTION
**Pull request by archermarx**
Partially addresses https://github.com/SciML/Surrogates.jl/issues/338

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Thanks!

**Comment by ChrisRackauckas** [comment]
Oh hmm, I didn't see the tests didn't actually ran. I saw green and merged 😓 . Looks like there's a test failure in the Kronecker?

**Comment by archermarx** [comment]
Hmm, will investigate and make a new PR

**Comment by archermarx** [comment]
Opened a new PR to fix and add additional tests https://github.com/SciML/QuasiMonteCarlo.jl/pull/21

**Pull request merged**
