### PR TITLE
Scrambled Faure Sequences

### PR DESCRIPTION
**Pull request by ParadaCarleton**
Faure sequences are now randomized!

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
`UndefVarError: Xoshiro not defined`, that was introduced in Julia v1.7, so for LTS you need `@static if VERSION <= v"1.7"`

**Comment by dmetivie** [comment]
Could we add the option `randomize = true/false`? This would correspond to `rng = InertSampler()` where `IntertSampler()` is written in your tests.

**Comment by dmetivie** [comment]
By the way, could you detail in code description the randomization method you use? I understand that you randomize as you create the Faure sequence, but do you know the randomization it corresponds to e.g. nested uniform scrambling?

**Comment by dmetivie** [comment]
I believe there is a problem in the randomization method, since it does not seem to preserve the `(0,m,d)`-sequence aspect.
See:
```julia
using QuasiMonteCarlo
using Random
using Plots
plot_font = "Computer Modern"
default(fontfamily=plot_font, linewidth=1, label=nothing, grid=true, framestyle=:default)

# Your InertSampler
struct InertSampler <: Random.AbstractRNG end
InertSampler(args...; kwargs...) = InertSampler()
Random.rand(::InertSampler, ::Type{T}) where {T} = zero(T)
Random.shuffle!(::InertSampler, arg::AbstractArray) = arg

m = 4
d = 3
b = QuasiMonteCarlo.nextprime(d)
n = b^m

# * Deterministic Faure * #
rng = InertSampler()
faure = permutedims(QuasiMonteCarlo.sample(n, d, FaureSample(rng)))
begin
    d1 = 1
    d2 = 2
    x = faure
    p = [plot(thickness_scaling=2, aspect_ratio=:equal) for i in 0:m]
    for i in 0:m
        j = m - i
        xᵢ = range(0, 1, step=1 / b^(i))
        xⱼ = range(0, 1, step=1 / b^(j))
        scatter!(p[i+1], x[:, d1], x[:, d2], ms=2, c=1, grid=false)
        xlims!(p[i+1], (0, 1.01))
        ylims!(p[i+1], (0, 1.01))
        yticks!(p[i+1], [0, 1])
        xticks!(p[i+1], [0, 1])
        hline!(p[i+1], xᵢ, c=:gray, alpha=0.2)
        vline!(p[i+1], xⱼ, c=:gray, alpha=0.2)
    end
    plot(p..., size=(1500, 900))
end
```
image

The pictures show 1 and only 1 point in each elementary rectangle, which confirm the `(0,m,d)`-sequence aspect, i.e. equidistribution property.

This is basically what is tested in your test + it corresponds to [Figure 20.2 p12](https://d1wqtxts1xzle7.cloudfront.net/53558076/Modeling_uncertainty._An_examination_of_20170617-2773-1ns5bxz-libre.pdf?1497712777=&response-content-disposition=inline%3B+filename%3DModeling_Uncertainty_An_Examination_of_S.pdf&Expires=1667230033&Signature=d36vhGJKL3lUW62qhRVUk6zbpNsykxmuy6nyfgAiFLFR0c3S2~G1Pm6h7PG74hzcbwibK9REW9Gd9-2~iudvfoaAAJWEqZoat8Yk4T8YKcvYT9UPtaTlyjx63qylZof0Q03Zq5HZG9X5baekHIblQIJ1OQKh4ZUfJpb3QDb7Enm5w7FKSjUV6BDUaWAb8r~MvcWkUNPvyEsSBBmXUdDSs59FZoCpNcOEAdd2rtcariekz~2Zxk3ydGcgJ6KGWzV8-OWdU8h5J9iEl1c1NdSYzDxmfMAsYjO~-Ye1mIjwtSUE-7hP41g1hYsHMRWzvButb8eaVQmWzMu~QiofKG~~Cg__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA)

Now with the randomization it not a `(0,m,d)` sequence anymore.
```julia
Random.seed!(3)
rng = Random.GLOBAL_RNG
faure = permutedims(QuasiMonteCarlo.sample(n, d, FaureSample(rng)))
```
image

**Comment by ParadaCarleton** [comment]
Oh hmm, I think you’re right. It’s odd that it ends up so close to a net but just barely misses, and even passes in the tests. It might be an off-by-one error, floating point error, or a problem with the last part of the randomization (where I add a small random float to simulate shuffling infinitely many digits at the end).

The code is supposed to implement a nested uniform (Owen) scrambling.

**Pull request merged**
