### PR TITLE
Uniform sample output size

### PR DESCRIPTION
**Pull request by luap-pik**
I noticed that the output size of `sample` for different algorithms is not uniform, which is a problem when they are changed a lot.

I edited the sample functions for GridSample, UniformSample, SobolSample and Distribution types
to achieve a common output size `(n, d)`. Here, `n` is the sample size and `d` the dimension of the sample space.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Thanks. Can you double check that upstream DiffEqSensitivity tests pass with this?

**Comment by ChrisRackauckas** [comment]
Indeed the DiffEqSensitivity tests fail. The reason is because the SobolSample had the right output form `(d,n)`. The reason this is the output form is because direct map benefit from this being column-major, i.e. `samples[:,i]` gives a valid sampling. I think the right way to do this would be to convert the other methods to this format.

**Comment by luap-pik** [comment]
Thank's for pointing this out, I took me some time to look into the DiffEqSensitivity tests.

 I changed the other methods to this form accordingly.

**Comment by ChrisRackauckas** [comment]
awesome job!

**Comment by luap-pik** [comment]
thank's! ;-)

**Pull request merged**
