### PR TITLE
Improve docs

### PR DESCRIPTION
**Pull request by ArnoStrouwen**

### CODE REVIEW

**Comment by dmetivie** [comment]
Hello, thanks for the correction.
Just curious, how do you use LanguageTool (inside VSCode? which extension) it seems that you got many more errors than I got with mine LT.

**Comment by ChrisRackauckas** [comment]
└ @ Documenter.DocChecks ~/.julia/packages/Documenter/bYYzK/src/Utilities/Utilities.jl:34
┌ Error: linkcheck 'https://d1wqtxts1xzle7.cloudfront.net/76482087/PUBLISHED_PAPER-libre.pdf?1639660270=&response-content-disposition=inline%3B+filename%3DVariance_based_sensitivity_analysis_of_m.pdf&Expires=1688379297&Signature=d5EIx-lAwTgdGaZwbquxELAzzZESzN3hfKE-XOlw1Zn7MkPgJ1m%7EoHhM2q0QJa4rOteYa%7E6eyJFVCcmSBWWvQBUHmik8OgopOQmpGGgUDRheg7tI1i1asKkxJ6mK4NAAX7smWW0sob8rknpbnqN8zG2XiIxDlJHj2NcWYDy1Xo0Gl2gkyHelLZHYhYJYlCWsOGzTKJrZEX5wFVdCT47C%7EpM5o5d7fb9zqjc6etMM%7EKuJVvyRilYPX5rO7cNEAPJgBXm-ODCBN8mUBHnWDcZtDqDAethmf%7E06H8za9vaYtX679v2E1ezE1FV9oA2GViViLXk94WNths7gHl5nmxw2Kw__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA' status: 403.
└ @ Documenter.DocChecks ~/.julia/packages/Documenter/bYYzK/src/Utilities/Utilities.jl:32
┌ Warning: linkcheck 'https://github.com/oschulz/UnsafeArrays.jl' status: 301, redirects to 'https://github.com/JuliaArrays/UnsafeArrays.jl'

It's pointing to this

```
!!! warning
    The method `generate_design_matrices(n, d, sampler, R::NoRand, num_mats, T = Float64)` is an ad hoc way to produce a Design Matrix. Indeed, it creates a deterministic point set in dimension `d × num_mats` and splits it into `num_mats` point set of dimension `d`. The resulting sequences have no QMC guarantees.
    This seems to have been proposed in Section 5.1 of [*Saltelli, A. et al. (2010)*](https://d1wqtxts1xzle7.cloudfront.net/76482087/PUBLISHED_PAPER-libre.pdf?1639660270=&response-content-disposition=inline%3B+filename%3DVariance_based_sensitivity_analysis_of_m.pdf&Expires=1685981169&Signature=aim5tHldlkb0ewZ9-gSMZsW2F1b88tLvV8euV1FpD61UYrE1mLR3RDERut0BsHNbcibjKQnF1JlsZ8mtEx~E1~eI3A~SOSySbpQllIpbhu556pFGUvD3GV5M6ghwa-5QMDP3-aQczBzflR721N4PCVJgqfmV-y94pkijQYvHSvZaPKb-tsoS8TVxE6H31Ptk4u662H61ofKzXR5JCHv0740qkQ0hORH~GqXOt8s7yQMVWYswZT4pWGSkJ9EehEQHCLo2uDVW-YSopwlSaaMRz~~0O~hkGAVE8sC~TAB7b5KnUgtNXl0jYTfGNTYO4GNJo1XhmHwj~Og~sBLDIXDxsg__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA)[^1] to do uncertainty quantification.
```

That link isn't defined.

**Comment by ChrisRackauckas** [comment]
Interesting, the new link works but gives a false positive?

**Comment by ArnoStrouwen** [comment]
It is because some sites block access when they think the user is a bot. I will just put them in the ignore.

**Comment by ArnoStrouwen** [comment]
> Hello, thanks for the correction. Just curious, how do you use LanguageTool (inside VSCode? which extension) it seems that you got many more errors than I got with mine LT.

I use LTeX – LanguageTool grammar/spell checking plugin for VScode by Julian Valentin.
Then I had to configure it with a server, for it to work well:
https://dev.languagetool.org/public-http-api
But I don't remember exactly how I did then, I remember it was a pain.

**Comment by ArnoStrouwen** [comment]
Why isn't my latest commit showing up here and retriggering CI?
https://github.com/SciML/QuasiMonteCarlo.jl/compare/master...ArnoStrouwen:QuasiMonteCarlo.jl:improve_docs

**Pull request closed without merging**
