### PR TITLE
Julia 1.10 maintenance

### PR DESCRIPTION
**Pull request by ArnoStrouwen**

### CODE REVIEW

**Comment by ArnoStrouwen** [comment]
New invalidation popped up in 1.10?

**Comment by ChrisRackauckas** [comment]
Yeah seems like it. Seems pretty innocuous though so I'd make note of what it is and if it doesn't have an easy fix just move on to the next repo.

**Comment by ArnoStrouwen** [comment]
I'm pretty inexpererienced with the snoopcompile stack.

Is my interpretation correct that this would have to be fixed upstream at DelimitedFiles?
```jl
julia> invalidation_trees(invalidations)
1-element Vector{SnoopCompile.MethodInvalidations}:
 inserting show(io::IO, ::MIME{Symbol("text/tab-separated-values")}, a) @ DelimitedFiles C:\Users\arno\.julia\packages\DelimitedFiles\aGcsu\src\DelimitedFiles.jl:835 invalidated:
   mt_backedges: 1: signature Tuple{typeof(show), IOContext{IOBuffer}, MIME, String} triggered MethodInstance for show(::IOContext{IOBuffer}, ::String, ::String) (0 children)
                 2: signature Tuple{typeof(show), IOContext{IOBuffer}, MIME, Base.BinaryPlatforms.Platform} triggered MethodInstance for show(::IOContext{IOBuffer}, ::String, ::Base.BinaryPlatforms.Platform) (0 children)
                 3: signature Tuple{typeof(show), IOContext{IOBuffer}, MIME, Int64} triggered MethodInstance for show(::IOContext{IOBuffer}, ::String, ::Int64) (0 
children)

julia> uinvalidated(invalidations)
Set{Core.MethodInstance} with 3 elements:
  MethodInstance for show(::IOContext{IOBuffer}, ::String, ::Int64)
  MethodInstance for show(::IOContext{IOBuffer}, ::String, ::String)
  MethodInstance for show(::IOContext{IOBuffer}, ::String, ::Base.BinaryPlatforms.Platform)

(QuasiMonteCarlo) pkg> why DelimitedFiles
  Sobol → DelimitedFiles
```

**Comment by ChrisRackauckas** [comment]
Oh so it's in Sobol.jl then.

**Pull request merged**
